name: Linting for accessibility issues

on: [pull_request]
# on:
#   push:
#     branches:
#       - main

# rules:
#   image-alt:
#     enabled: true
#     severity: error
#   # label:
#   #   enabled: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dequelabs/axe-linter-action@v1
        with:
          api_key: ${{ secrets.LINTER_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
